version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: deaca-db
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DB_NAME}
    ports:
      - '${TYPEORM_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deaca-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deaca-api
    ports:
      - '4003:4003'
    depends_on:
      - postgres
    environment:
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DB_NAME: ${TYPEORM_DB_NAME}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_HOST: postgres
    networks:
      - deaca-network

volumes:
  postgres_data:

networks:
  deaca-network:
    driver: bridge
