version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: deaca-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - deaca-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deaca-api
    ports:
      - '4003:4003'
    depends_on:
      - postgres
    environment:
      TYPEORM_USERNAME: ${DATABASE_USER}
      TYPEORM_PASSWORD: ${DATABASE_PASS}
      TYPEORM_DB_NAME: ${DATABASE_NAME}
      TYPEORM_PORT: ${DATABASE_PORT}
      TYPEORM_HOST: postgres
    networks:
      - deaca-network

volumes:
  postgres_data:

networks:
  deaca-network:
    driver: bridge
